name: Process Website Creation
on: 
  issues:
    types: [opened]
jobs:
  create_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/create-website.yml
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > website-info.json
      - run: cat website-info.json
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      - run: python .github/workflows/convert_to_csv.py
      - run: bash bash.sh website-info.csv
